# wrangler.toml

name = "wangdeting-weight-tracker" # Replace with your desired worker name
main = "functions/api/[[path]].js"  # Entry point for Functions
compatibility_date = "2023-10-30" # Use a recent compatibility date

# KV Namespace binding
# Important: You need to create this KV namespace in your Cloudflare dashboard
# and then uncomment and update the binding here.
[[kv_namespaces]]
binding = "WEIGHT_LOG_KV"
id = "YOUR_KV_NAMESPACE_ID" # Replace with your actual KV namespace ID
# preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" # Optional: For wrangler dev

# If deploying as a Pages Function (recommended for this setup)
# No explicit [site] section is needed as Pages handles this.
# Just ensure your build command (if any) outputs to the correct directory
# and this wrangler.toml is in the root.

# If deploying as a standalone Worker with site assets:
# [site]
# bucket = "./" # Or your build output directory (e.g., "./dist")

# Optional: wrangler dev configuration
# [dev]
# ip = "localhost"
# port = 8788
# local_protocol = "http"
# kv_persist = ".wrangler/state/v3/kv" # Persist KV data locally 